// generated by ui/build.py — do not edit by hand
window.CATALOG = {
 "generated_at": "2026-09-18 15:01",
 "git": true,
 "marketplace": {
  "name": "acb",
  "repo": "innowise-ai/ai-ml-accelerator"
 },
 "session_model": {
  "_": "The typical session the «Token cost» column is measured against: turns model calls, each with context_tokens of input and output_tokens of output. Δ% = (standing cost × turns + per-call cost × calls + behavioural effect) / (turns × (context + output)). MCP: if the tool schemas exceed mcp_defer_over_tokens, Claude Code loads them deferred and only the names stay in context (mcp_deferred_tokens_per_tool per tool).",
  "turns": 40,
  "context_tokens": 30000,
  "output_tokens": 600,
  "mcp_defer_over_tokens": 5000,
  "mcp_deferred_tokens_per_tool": 15
 },
 "verdicts": {
  "must-have": {
   "label": "Must have",
   "hint": "into any project by default: almost always pays off, no conditions"
  },
  "stack": {
   "label": "For the stack",
   "hint": "if the project uses the technology or service from the description"
  },
  "task": {
   "label": "For a task",
   "hint": "for the duration of a specific job, then remove; usually expensive on activation"
  },
  "taste": {
   "label": "Taste",
   "hint": "a person's working style, not the project's; install into ~/.claude"
  },
  "no": {
   "label": "Don't install",
   "hint": "rejected by the reviewer; the entry stays as a warning"
  }
 },
 "kinds": [
  {
   "kind": "skill",
   "label": "Skills"
  },
  {
   "kind": "agent",
   "label": "Agents"
  },
  {
   "kind": "mcp",
   "label": "MCP servers"
  },
  {
   "kind": "hook",
   "label": "Hooks"
  },
  {
   "kind": "plugin",
   "label": "Plugins"
  }
 ],
 "library": {
  "skill": [
   "bigquery-basics",
   "build-review-interface",
   "caveman",
   "claude-api",
   "cloud-sql-basics",
   "deep-agents-core",
   "deep-agents-memory",
   "deep-agents-orchestration",
   "deepagents-python-quickstart",
   "deepagents-typescript-quickstart",
   "docx",
   "ecosystem-primer",
   "error-discovery",
   "eval-audit",
   "eval-engineering",
   "evals-start",
   "evaluate-rag",
   "generate-synthetic-data",
   "google-cloud-recipe-auth",
   "langchain-dependencies",
   "langchain-fundamentals",
   "langchain-middleware",
   "langchain-python-quickstart",
   "langchain-rag",
   "langchain-typescript-quickstart",
   "langgraph-cli",
   "langgraph-fundamentals",
   "langgraph-human-in-the-loop",
   "langgraph-persistence",
   "langgraph-python-quickstart",
   "langgraph-typescript-quickstart",
   "langsmith-online-eval-engineering",
   "managed-deep-agents",
   "mcp-builder",
   "qdrant-clients-sdk",
   "qdrant-deployment-options",
   "qdrant-edge",
   "qdrant-migration-tool",
   "qdrant-model-migration",
   "qdrant-monitoring",
   "qdrant-multitenancy",
   "qdrant-performance-optimization",
   "qdrant-scaling",
   "qdrant-search-quality",
   "qdrant-sizing",
   "qdrant-version-upgrade",
   "skill-creator",
   "swarm",
   "validate-evaluator",
   "write-judge-prompt"
  ],
  "agent": [],
  "mcp": [
   "context7",
   "github"
  ],
  "hook": [
   "notify-done"
  ]
 },
 "compositions": {
  "base": {
   "skill": [],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "evals": {
   "skill": [
    "evals-start",
    "eval-audit",
    "error-discovery",
    "write-judge-prompt",
    "validate-evaluator",
    "generate-synthetic-data",
    "evaluate-rag",
    "build-review-interface"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "gcp": {
   "skill": [
    "bigquery-basics",
    "cloud-sql-basics",
    "google-cloud-recipe-auth"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "langchain": {
   "skill": [
    "deep-agents-core",
    "deep-agents-memory",
    "deep-agents-orchestration",
    "deepagents-python-quickstart",
    "deepagents-typescript-quickstart",
    "ecosystem-primer",
    "eval-engineering",
    "langchain-dependencies",
    "langchain-fundamentals",
    "langchain-middleware",
    "langchain-python-quickstart",
    "langchain-rag",
    "langchain-typescript-quickstart",
    "langgraph-cli",
    "langgraph-fundamentals",
    "langgraph-human-in-the-loop",
    "langgraph-persistence",
    "langgraph-python-quickstart",
    "langgraph-typescript-quickstart",
    "langsmith-online-eval-engineering",
    "managed-deep-agents",
    "swarm"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "qdrant": {
   "skill": [
    "qdrant-clients-sdk",
    "qdrant-deployment-options",
    "qdrant-edge",
    "qdrant-migration-tool",
    "qdrant-model-migration",
    "qdrant-monitoring",
    "qdrant-multitenancy",
    "qdrant-performance-optimization",
    "qdrant-scaling",
    "qdrant-search-quality",
    "qdrant-sizing",
    "qdrant-version-upgrade"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  }
 },
 "items": [
  {
   "id": "hook-notify-done",
   "kind": "hook",
   "name": "notify-done",
   "dir": "catalog/hook-notify-done",
   "status": "reviewed",
   "members": [
    {
     "kind": "hook",
     "name": "notify-done",
     "path": "lib/hooks/notify-done",
     "description": null,
     "events": [
      "Stop"
     ],
     "scripts": [
      "notify-done.sh"
     ]
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "taste",
    "rating": 4,
    "security": 5,
    "economy": "0%",
    "body": "## Summary\nWhen several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing.\n\n## Notes\nCustom hook on the Stop event; osascript on macOS, notify-send on Linux, no network\nDoes not land in the prompt — 0 tokens",
    "use": "When several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing."
   },
   "view": {
    "title": "notify-done",
    "verdict": "taste",
    "pitch": "When several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing.",
    "sections": [
     {
      "title": "Notes",
      "text": "Custom hook on the Stop event; osascript on macOS, notify-send on Linux, no network\nDoes not land in the prompt — 0 tokens"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 4,
   "size": null,
   "security": 5,
   "economy": {
    "always_on": 0,
    "partial": false,
    "idle_pct": 0,
    "pct": 0,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/hooks/notify-done"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/lib/hooks/notify-done",
    "label": "lib/hooks/notify-done",
    "repo": null
   },
   "install": {
    "id": "notify-done@acb",
    "cmd": "claude plugin install notify-done@acb",
    "try": "claude --plugin-dir catalog/hook-notify-done"
   },
   "artifact": null
  },
  {
   "id": "mcp-context7",
   "kind": "mcp",
   "name": "context7",
   "dir": "catalog/mcp-context7",
   "status": "reviewed",
   "members": [
    {
     "kind": "mcp",
     "name": "context7",
     "path": "lib/mcp/context7.json",
     "description": null,
     "type": "http",
     "url": "https://mcp.context7.com/mcp",
     "command": null,
     "env_required": []
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "must-have",
    "rating": 5,
    "security": 4,
    "economy": "+4%",
    "full-body": "1.2k",
    "body": "## Summary\nPulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off.\n\n## Examples\n- We want to build an agent on LangGraph => with it, takes the modern create_agent abstraction from langchain v1 instead of a tool loop from scratch\n- Updated the Vercel AI SDK, `maxSteps` is gone => without it, writes `stepCountIs` from v5 from memory, with it, takes the current `isStepCount`\n\n## Notes\nOne of the most popular and convenient MCPs;\nThe answer averages 3.5k tokens (on average 3-5 per session)\nFires almost always (for me ~80% of sessions)\nSafe; only the library name and the topic of the request go out, no code goes out",
    "use": "Pulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off."
   },
   "view": {
    "title": "context7",
    "verdict": "must-have",
    "pitch": "Pulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off.",
    "sections": [
     {
      "title": "Examples",
      "text": "- We want to build an agent on LangGraph => with it, takes the modern create_agent abstraction from langchain v1 instead of a tool loop from scratch\n- Updated the Vercel AI SDK, `maxSteps` is gone => without it, writes `stepCountIs` from v5 from memory, with it, takes the current `isStepCount`"
     },
     {
      "title": "Notes",
      "text": "One of the most popular and convenient MCPs;\nThe answer averages 3.5k tokens (on average 3-5 per session)\nFires almost always (for me ~80% of sessions)\nSafe; only the library name and the topic of the request go out, no code goes out"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 1200,
   "security": 4,
   "economy": {
    "always_on": null,
    "partial": false,
    "idle_pct": null,
    "pct": 4,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-langchain-create-agent",
     "02-ai-sdk-stop-condition"
    ],
    "runs": 1,
    "latest": {
     "score": 1,
     "delta": 0.5833333333333334,
     "pass_rate": 1,
     "cases": 2,
     "passed": 2,
     "cost_usd": 0.8477839999999999,
     "version": "2.1.272",
     "at": "2026-09-15",
     "partial": false,
     "report": "catalog/mcp-context7/evals/results/2026-09-15T09-41-46-156Z/report.html",
     "dir": "catalog/mcp-context7/evals/results/2026-09-15T09-41-46-156Z",
     "per_case": [
      {
       "name": "01-langchain-create-agent",
       "score": 1,
       "without": 0.5,
       "delta": 0.5
      },
      {
       "name": "02-ai-sdk-stop-condition",
       "score": 1,
       "without": 0.3333333333333333,
       "delta": 0.6666666666666667
      }
     ]
    },
    "cmd": "python3 ui/eval.py lib/mcp/context7.json"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/upstash/context7",
    "label": "upstash/context7",
    "repo": "upstash/context7"
   },
   "install": {
    "id": "context7@acb",
    "cmd": "claude plugin install context7@acb",
    "try": "claude --plugin-dir catalog/mcp-context7"
   },
   "artifact": null
  },
  {
   "id": "mcp-github",
   "kind": "mcp",
   "name": "github",
   "dir": "catalog/mcp-github",
   "status": "reviewed",
   "members": [
    {
     "kind": "mcp",
     "name": "github",
     "path": "lib/mcp/github.json",
     "description": null,
     "type": "http",
     "url": "https://api.githubcopilot.com/mcp/",
     "command": null,
     "env_required": [
      "GITHUB_PAT"
     ]
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "must-have",
    "rating": 5,
    "security": 3.5,
    "economy": "+3%",
    "full-body": 600,
    "body": "## Summary\nWhen the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions\n\n## Examples\n- \"Open a PR from this branch and reply to the reviewer\" => `create_pull_request` and `add_reply_to_pull_request_comment` straight from the session, without gh CLI and without the web\n- CI failed => `get_job_logs` with `failed_only: true` returns the logs of every failed job of one run, instead of copy-paste from Actions or switching to browser using tools\n\n## Notes\nI use it constantly\nSchemas of ~40 tools ≈ 18k tok, but Claude Code loads them deferred: ≈ 600 tok of names in the context, the schema is pulled in on call\nThe token goes only to the official GitHub server, where the code already lives anyway",
    "use": "When the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions"
   },
   "view": {
    "title": "github",
    "verdict": "must-have",
    "pitch": "When the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Open a PR from this branch and reply to the reviewer\" => `create_pull_request` and `add_reply_to_pull_request_comment` straight from the session, without gh CLI and without the web\n- CI failed => `get_job_logs` with `failed_only: true` returns the logs of every failed job of one run, instead of copy-paste from Actions or switching to browser using tools"
     },
     {
      "title": "Notes",
      "text": "I use it constantly\nSchemas of ~40 tools ≈ 18k tok, but Claude Code loads them deferred: ≈ 600 tok of names in the context, the schema is pulled in on call\nThe token goes only to the official GitHub server, where the code already lives anyway"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 600,
   "security": 3.5,
   "economy": {
    "always_on": null,
    "partial": false,
    "idle_pct": null,
    "pct": 3,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/mcp/github.json"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/github/github-mcp-server",
    "label": "github/github-mcp-server",
    "repo": "github/github-mcp-server"
   },
   "install": {
    "id": "github@acb",
    "cmd": "claude plugin install github@acb",
    "try": "claude --plugin-dir catalog/mcp-github"
   },
   "artifact": null
  },
  {
   "id": "plugin-base",
   "kind": "plugin",
   "name": "base",
   "dir": "catalog/plugin-base",
   "status": "draft",
   "members": [],
   "bundles": [],
   "review": null,
   "view": {
    "title": "base",
    "verdict": null,
    "pitch": null,
    "sections": [],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": null,
   "size": null,
   "security": null,
   "economy": {
    "always_on": 0,
    "partial": false,
    "idle_pct": 0,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/plugins/base.json"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/catalog/plugin-base/REVIEW.md",
    "label": "catalog/plugin-base/REVIEW.md",
    "repo": null
   },
   "install": {
    "id": "base@acb",
    "cmd": "claude plugin install base@acb",
    "try": "claude --plugin-dir catalog/plugin-base"
   },
   "artifact": null
  },
  {
   "id": "plugin-evals",
   "kind": "plugin",
   "name": "evals",
   "dir": "catalog/plugin-evals",
   "status": "draft",
   "members": [
    {
     "kind": "skill",
     "name": "evals-start",
     "path": "lib/skills/evals-start",
     "description": "Entry point for evals. Use when the user asks for help with evals, does not know where to begin, or asks for something no other skill in this plugin matches. Do NOT use when a more specific skill in this plugin already matches; load that skill directly.",
     "tokens_meta": 66,
     "tokens_body": 384,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "eval-audit",
     "path": "lib/skills/eval-audit",
     "description": "Audit an LLM eval pipeline and surface problems: missing error analysis, unvalidated judges, vanity metrics, etc. Use when inheriting an eval system, when unsure whether evals are trustworthy, or as a starting point when no eval infrastructure exists. Do NOT use when the goal is to build a new evaluator from scratch (use error-discovery, write-judge-prompt, or validate-evaluator instead).",
     "tokens_meta": 100,
     "tokens_body": 2489,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "error-discovery",
     "path": "lib/skills/error-discovery",
     "description": "Run error analysis on a dataset. Build a review UI, select diverse samples, monitor annotations, and organize failure modes.",
     "tokens_meta": 35,
     "tokens_body": 3732,
     "tokens_dir": 1481,
     "files": 2,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "write-judge-prompt",
     "path": "lib/skills/write-judge-prompt",
     "description": "Design LLM-as-Judge evaluators for subjective criteria that code-based checks cannot handle. Use when a failure mode requires interpretation (tone, faithfulness, relevance, completeness). Do NOT use when the failure mode can be checked with code (regex, schema validation, execution tests). Do NOT use when you need to validate or calibrate the judge — use validate-evaluator instead.",
     "tokens_meta": 101,
     "tokens_body": 1924,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "validate-evaluator",
     "path": "lib/skills/validate-evaluator",
     "description": "Calibrate an LLM judge against human labels using data splits, TPR/TNR, and bias correction. Use after writing a judge prompt (write-judge-prompt) when you need to verify alignment before trusting its outputs. Do NOT use for code-based evaluators (those are deterministic; test with standard unit tests).",
     "tokens_meta": 81,
     "tokens_body": 2222,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "generate-synthetic-data",
     "path": "lib/skills/generate-synthetic-data",
     "description": "Create diverse synthetic test inputs for LLM pipeline evaluation using dimension-based tuple generation. Use when bootstrapping an eval dataset, when real user data is sparse, or when stress-testing specific failure hypotheses. Do NOT use when you already have 100+ representative real traces (use stratified sampling instead), or when the task is collecting production logs.",
     "tokens_meta": 100,
     "tokens_body": 1353,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "evaluate-rag",
     "path": "lib/skills/evaluate-rag",
     "description": "Guides evaluation of RAG pipeline retrieval and generation quality. Use when evaluating a retrieval-augmented generation system, measuring retrieval quality, assessing generation faithfulness or relevance, generating synthetic QA pairs for retrieval testing, or optimizing chunking strategies.",
     "tokens_meta": 76,
     "tokens_body": 1906,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "build-review-interface",
     "path": "lib/skills/build-review-interface",
     "description": "Build a custom browser-based annotation interface tailored to your data for reviewing LLM traces and collecting structured feedback. Use when you need to build an annotation tool, review traces, or collect human labels.",
     "tokens_meta": 60,
     "tokens_body": 1352,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": null,
   "view": {
    "title": "evals",
    "verdict": null,
    "pitch": null,
    "sections": [],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": null,
   "size": null,
   "security": null,
   "economy": {
    "always_on": 619,
    "partial": false,
    "idle_pct": 2.0228758169934644,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-route-traces-in-hand",
     "02-route-no-traces-yet",
     "03-audit-likert-holistic-judge",
     "04-audit-accuracy-under-imbalance",
     "05-audit-fewshot-leakage",
     "06-audit-similarity-metric",
     "07-audit-greenfield-no-evals",
     "08-judge-four-components",
     "09-judge-should-be-code",
     "10-judge-spec-failure",
     "11-judge-fewshot-source",
     "12-judge-holistic-trace",
     "13-validate-agreement-metric",
     "14-validate-correction-invalid",
     "15-validate-interval-and-sample",
     "16-validate-test-set-once",
     "17-validate-splits-and-labeller",
     "18-synth-dimensions-and-tuples",
     "19-synth-arbitrary-dimensions",
     "20-synth-wrong-tool",
     "21-rag-separate-stages",
     "22-rag-rerank-metrics",
     "23-rag-chunking-search",
     "24-rag-faithfulness-definition",
     "25-discovery-noninteractive-honesty",
     "26-discovery-sampling-composition",
     "27-discovery-freetext-first",
     "28-discovery-premature-scan",
     "29-review-interface-rendering",
     "30-neg-foundation-benchmark",
     "31-neg-unit-test-request",
     "32-neg-latency-regression"
    ],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/plugins/evals.json"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/catalog/plugin-evals/REVIEW.md",
    "label": "catalog/plugin-evals/REVIEW.md",
    "repo": null
   },
   "install": {
    "id": "evals@acb",
    "cmd": "claude plugin install evals@acb",
    "try": "claude --plugin-dir catalog/plugin-evals"
   },
   "artifact": null
  },
  {
   "id": "plugin-gcp",
   "kind": "plugin",
   "name": "gcp",
   "dir": "catalog/plugin-gcp",
   "status": "draft",
   "members": [
    {
     "kind": "skill",
     "name": "bigquery-basics",
     "path": "lib/skills/bigquery-basics",
     "description": "Manages datasets, tables, and jobs in BigQuery. Use when you need to interact with BigQuery, run SQL queries, manage BigQuery resources (datasets, tables, views), or perform basic data ingestion and analysis.",
     "tokens_meta": 56,
     "tokens_body": 1052,
     "tokens_dir": 5024,
     "files": 9,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "cloud-sql-basics",
     "path": "lib/skills/cloud-sql-basics",
     "description": "This file generates or explains Cloud SQL resources. Use this file when the user asks to create a Cloud SQL instance or database for MySQL, PostgreSQL, or SQL Server. Cloud SQL manages third-party MySQL, PostgreSQL, and SQL Server instances as resources in Cloud SQL. For example, when Cloud SQL creates an open-source MySQL instance, the resulting resource is a Cloud SQL for MySQL instance that Google Cloud manages. Cloud SQL handles backups, high availability, and secure connectivity for relational database workloads.",
     "tokens_meta": 135,
     "tokens_body": 968,
     "tokens_dir": 9568,
     "files": 8,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "google-cloud-recipe-auth",
     "path": "lib/skills/google-cloud-recipe-auth",
     "description": "Provides expert guidance on authenticating and authorizing to Google Cloud services and APIs, covering human users, service identities, Application Default Credentials (ADC), and best practices for secure access.",
     "tokens_meta": 59,
     "tokens_body": 3054,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "draft": true,
    "title": null,
    "url": null,
    "verdict": "task",
    "rating": 3,
    "security": 4,
    "economy": null,
    "full-body": null,
    "category": null,
    "tags": [],
    "body": "## Summary\nWhen you are working with GCP BigQuery, CloudSQl or have authorization/authentification issues. Useful for both working in existing infrastructure or setting up a new one.\n\n## Examples\nThe plugin fixes invented flags, without it the model may produce names not used for instance creation etc. \nImpersonation, permissions errors and authentification issues in general, plugin provides more information that helped me to resolve my issues. \n\n## Notes\nContents: skill/bigquery-basics, skill/cloud-sql-basics, skill/google-cloud-recipe-auth.",
    "use": "When you are working with GCP BigQuery, CloudSQl or have authorization/authentification issues. Useful for both working in existing infrastructure or setting up a new one."
   },
   "view": {
    "title": "gcp",
    "verdict": "task",
    "pitch": "When you are working with GCP BigQuery, CloudSQl or have authorization/authentification issues. Useful for both working in existing infrastructure or setting up a new one.",
    "sections": [
     {
      "title": "Examples",
      "text": "The plugin fixes invented flags, without it the model may produce names not used for instance creation etc. \nImpersonation, permissions errors and authentification issues in general, plugin provides more information that helped me to resolve my issues."
     },
     {
      "title": "Notes",
      "text": "Contents: skill/bigquery-basics, skill/cloud-sql-basics, skill/google-cloud-recipe-auth."
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 3,
   "size": null,
   "security": 4,
   "economy": {
    "always_on": 250,
    "partial": false,
    "idle_pct": 0.8169934640522877,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-cloudsql-create-instance",
     "02-auth-outside-gcp",
     "03-cloudsql-read-pool",
     "04-bigquery-change-history",
     "05-cloudsql-compliance-retention",
     "06-bigquery-continuous-queries",
     "07-impersonation-no-user-email",
     "08-no-console-terminal-only",
     "09-adc-precedence-error",
     "10-quota-project-warning",
     "11-quota-project-permission",
     "12-impersonation-through-connector",
     "13-403-diagnosis",
     "14-bigquery-cost-cap",
     "15-bigquery-readonly-role",
     "16-bigquery-latest-value-per-series"
    ],
    "runs": 3,
    "latest": {
     "score": 0.9583333333333333,
     "delta": 0.06458333333333333,
     "pass_rate": 0.875,
     "cases": 16,
     "passed": 14,
     "cost_usd": 2.563752,
     "version": "2.1.276",
     "at": "2026-09-18",
     "partial": false,
     "report": "catalog/plugin-gcp/evals/results/2026-09-18T14-24-34-348Z/report.html",
     "dir": "catalog/plugin-gcp/evals/results/2026-09-18T14-24-34-348Z",
     "per_case": [
      {
       "name": "01-cloudsql-create-instance",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "02-auth-outside-gcp",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "03-cloudsql-read-pool",
       "score": 1,
       "without": 0.5,
       "delta": 0.5
      },
      {
       "name": "04-bigquery-change-history",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "05-cloudsql-compliance-retention",
       "score": 1,
       "without": 0.8,
       "delta": 0.19999999999999996
      },
      {
       "name": "06-bigquery-continuous-queries",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "07-impersonation-no-user-email",
       "score": 1,
       "without": 0.6666666666666666,
       "delta": 0.33333333333333337
      },
      {
       "name": "08-no-console-terminal-only",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "09-adc-precedence-error",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "10-quota-project-warning",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "11-quota-project-permission",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "12-impersonation-through-connector",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "13-403-diagnosis",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "14-bigquery-cost-cap",
       "score": 0.6666666666666666,
       "without": 0.6666666666666666,
       "delta": 0
      },
      {
       "name": "15-bigquery-readonly-role",
       "score": 1,
       "without": 1,
       "delta": 0
      },
      {
       "name": "16-bigquery-latest-value-per-series",
       "score": 0.6666666666666666,
       "without": 0.6666666666666666,
       "delta": 0
      }
     ]
    },
    "cmd": "python3 ui/eval.py lib/plugins/gcp.json"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/catalog/plugin-gcp/REVIEW.md",
    "label": "catalog/plugin-gcp/REVIEW.md",
    "repo": null
   },
   "install": {
    "id": "gcp@acb",
    "cmd": "claude plugin install gcp@acb",
    "try": "claude --plugin-dir catalog/plugin-gcp"
   },
   "artifact": null
  },
  {
   "id": "plugin-langchain",
   "kind": "plugin",
   "name": "langchain",
   "dir": "catalog/plugin-langchain",
   "status": "draft",
   "members": [
    {
     "kind": "skill",
     "name": "deep-agents-core",
     "path": "lib/skills/deep-agents-core",
     "description": "INVOKE THIS SKILL when building ANY Deep Agents application. Covers create_deep_agent(), harness architecture, SKILL.md format, and configuration options.",
     "tokens_meta": 43,
     "tokens_body": 3066,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "deep-agents-memory",
     "path": "lib/skills/deep-agents-memory",
     "description": "INVOKE THIS SKILL when your Deep Agent needs memory, persistence, or filesystem access. Covers StateBackend (ephemeral), StoreBackend (persistent), FilesystemMiddleware, and CompositeBackend for routing.",
     "tokens_meta": 55,
     "tokens_body": 2490,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "deep-agents-orchestration",
     "path": "lib/skills/deep-agents-orchestration",
     "description": "INVOKE THIS SKILL when using subagents, task planning, or human approval in Deep Agents. Covers SubAgentMiddleware, TodoList for planning, and HITL interrupts.",
     "tokens_meta": 46,
     "tokens_body": 3434,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "deepagents-python-quickstart",
     "path": "lib/skills/deepagents-python-quickstart",
     "description": "Scaffold a minimal local Deep Agent in Python by following the official quickstart, using provider-native web search instead of Tavily. Use when the user wants to quickly build or try a Deep Agent locally.",
     "tokens_meta": 58,
     "tokens_body": 549,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "deepagents-typescript-quickstart",
     "path": "lib/skills/deepagents-typescript-quickstart",
     "description": "Scaffold a minimal local Deep Agent in TypeScript by following the official quickstart, using provider-native web search instead of Tavily. Use when the user wants to quickly build or try a Deep Agent locally.",
     "tokens_meta": 60,
     "tokens_body": 548,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "ecosystem-primer",
     "path": "lib/skills/ecosystem-primer",
     "description": "INVOKE FIRST for any LangChain / LangGraph / Deep Agents agent building project before consulting other skills or writing any agent code. Required starting point for up to date info on framework selection (LangChain vs LangGraph vs Deep Agents vs hybrid composition), agent patterns, install, environment setup, and which skill to load next.",
     "tokens_meta": 89,
     "tokens_body": 2008,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "eval-engineering",
     "path": "lib/skills/eval-engineering",
     "description": "Inspect an agent repository and optional traces, interview the user, write reviewed Task Specs, build and audit Harbor tasks, and bootstrap reusable project World Knowledge Skills. Use for agent evals, benchmark design, Task generation, controlled Environments, synthetic data, Verifiers, Harbor runs, calibration, or continuous benchmark maintenance.",
     "tokens_meta": 92,
     "tokens_body": 3966,
     "tokens_dir": 38723,
     "files": 21,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-dependencies",
     "path": "lib/skills/langchain-dependencies",
     "description": "INVOKE THIS SKILL when setting up a new project or when asked about package versions, installation, or dependency management for LangChain, LangGraph, LangSmith, or Deep Agents. Covers required packages, minimum versions, environment requirements, versioning best practices, and common community tool packages for both Python and TypeScript.",
     "tokens_meta": 91,
     "tokens_body": 3635,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-fundamentals",
     "path": "lib/skills/langchain-fundamentals",
     "description": "Create LangChain agents with create_agent, define tools, and use middleware for human-in-the-loop and error handling.",
     "tokens_meta": 35,
     "tokens_body": 3130,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-middleware",
     "path": "lib/skills/langchain-middleware",
     "description": "INVOKE THIS SKILL when you need human-in-the-loop approval, custom middleware, or structured output. Covers HumanInTheLoopMiddleware for human approval of dangerous tool calls, creating custom middleware with hooks, Command resume patterns, and structured output with Pydantic/Zod.",
     "tokens_meta": 75,
     "tokens_body": 2690,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-python-quickstart",
     "path": "lib/skills/langchain-python-quickstart",
     "description": "Scaffold a minimal local LangChain agent in Python by following the official quickstart. Use when the user wants to quickly build or try a LangChain agent locally.",
     "tokens_meta": 48,
     "tokens_body": 368,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-rag",
     "path": "lib/skills/langchain-rag",
     "description": "INVOKE THIS SKILL when building ANY retrieval-augmented generation (RAG) system. Covers document loaders, RecursiveCharacterTextSplitter, embeddings (OpenAI), and vector stores (Chroma, FAISS, Pinecone).",
     "tokens_meta": 54,
     "tokens_body": 3856,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langchain-typescript-quickstart",
     "path": "lib/skills/langchain-typescript-quickstart",
     "description": "Scaffold a minimal local LangChain agent in TypeScript by following the official quickstart. Use when the user wants to quickly build or try a LangChain agent locally.",
     "tokens_meta": 50,
     "tokens_body": 376,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-cli",
     "path": "lib/skills/langgraph-cli",
     "description": "INVOKE THIS SKILL when using the langgraph CLI to scaffold, develop, build, or deploy LangGraph applications. Covers langgraph new, dev, build, up, deploy, and langgraph.json configuration.",
     "tokens_meta": 51,
     "tokens_body": 2788,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-fundamentals",
     "path": "lib/skills/langgraph-fundamentals",
     "description": "INVOKE THIS SKILL when writing ANY LangGraph code. Covers StateGraph, state schemas, nodes, edges, Command, Send, invoke, streaming, and error handling.",
     "tokens_meta": 44,
     "tokens_body": 5753,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-human-in-the-loop",
     "path": "lib/skills/langgraph-human-in-the-loop",
     "description": "INVOKE THIS SKILL when implementing human-in-the-loop patterns, pausing for approval, or handling errors in LangGraph. Covers interrupt(), Command(resume=...), approval/validation workflows, and the 4-tier error handling strategy.",
     "tokens_meta": 64,
     "tokens_body": 4088,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-persistence",
     "path": "lib/skills/langgraph-persistence",
     "description": "INVOKE THIS SKILL when your LangGraph needs to persist state, remember conversations, travel through history, or configure subgraph checkpointer scoping. Covers checkpointers, thread_id, time travel, Store, and subgraph persistence modes.",
     "tokens_meta": 65,
     "tokens_body": 4626,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-python-quickstart",
     "path": "lib/skills/langgraph-python-quickstart",
     "description": "Scaffold a minimal local LangGraph agent in Python by following the official quickstart. Use when the user wants to quickly build or try a LangGraph agent locally.",
     "tokens_meta": 48,
     "tokens_body": 453,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langgraph-typescript-quickstart",
     "path": "lib/skills/langgraph-typescript-quickstart",
     "description": "Scaffold a minimal local LangGraph agent in TypeScript by following the official quickstart. Use when the user wants to quickly build or try a LangGraph agent locally.",
     "tokens_meta": 50,
     "tokens_body": 455,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "langsmith-online-eval-engineering",
     "path": "lib/skills/langsmith-online-eval-engineering",
     "description": "Iteratively inspect traces, interview the user, and create LangSmith online evaluators one at a time. Use specifically for creating online evaluators for use within LangSmith -- use \"eval-engineering\" for Harbor-style online evaluations.",
     "tokens_meta": 68,
     "tokens_body": 1610,
     "tokens_dir": 4594,
     "files": 4,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "managed-deep-agents",
     "path": "lib/skills/managed-deep-agents",
     "description": "INVOKE THIS SKILL when building, testing, or deploying Managed Deep Agents in LangSmith with the mda CLI. Walks a user through their first agent end to end — interviewing them about what they want to build, mapping it onto what MDA can actually do, then scaffolding and deploying it. Covers the file-based project layout; define_deep_agent / defineDeepAgent; instructions, skills, memory, identity, tools, middleware, sandboxes, schedules, channels, and evals; mda init/build/dev/deploy/logs/delete; and Context Hub.",
     "tokens_meta": 134,
     "tokens_body": 7453,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "swarm",
     "path": "lib/skills/swarm",
     "description": "Dispatches many independent items in parallel: create a table, fan out to subagents, aggregate results. One row = one unit of work.",
     "tokens_meta": 34,
     "tokens_body": 2999,
     "tokens_dir": 13751,
     "files": 9,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": null,
   "view": {
    "title": "langchain",
    "verdict": null,
    "pitch": null,
    "sections": [],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": null,
   "size": null,
   "security": null,
   "economy": {
    "always_on": 1354,
    "partial": false,
    "idle_pct": 4.42483660130719,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/plugins/langchain.json"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/catalog/plugin-langchain/REVIEW.md",
    "label": "catalog/plugin-langchain/REVIEW.md",
    "repo": null
   },
   "install": {
    "id": "langchain@acb",
    "cmd": "claude plugin install langchain@acb",
    "try": "claude --plugin-dir catalog/plugin-langchain"
   },
   "artifact": null
  },
  {
   "id": "plugin-qdrant",
   "kind": "plugin",
   "name": "qdrant",
   "dir": "catalog/plugin-qdrant",
   "status": "draft",
   "members": [
    {
     "kind": "skill",
     "name": "qdrant-clients-sdk",
     "path": "lib/skills/qdrant-clients-sdk",
     "description": "Qdrant provides client SDKs for various programming languages, allowing easy integration with Qdrant deployments.",
     "tokens_meta": 33,
     "tokens_body": 752,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-deployment-options",
     "path": "lib/skills/qdrant-deployment-options",
     "description": "Guides Qdrant deployment selection. Use when someone asks 'how to deploy Qdrant', 'Docker vs Cloud', 'local mode', 'embedded Qdrant', 'Qdrant EDGE', 'which deployment option', 'self-hosted vs cloud', or 'need lowest latency deployment'. Also use when choosing between deployment types for a new project.",
     "tokens_meta": 82,
     "tokens_body": 976,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-edge",
     "path": "lib/skills/qdrant-edge",
     "description": "Guides building on Qdrant Edge, the embedded in-process shard. Use when someone asks 'how to sync Edge with the server', 'keep a local shard in sync with Qdrant Cloud', 'BM25 or keyword search on Edge', 'hybrid search on Edge', 'embeddings on device', 'Edge snapshots', 'apply a partial snapshot', 'why is my Edge search empty after inserts', or is writing custom sync, BM25, or fusion code against qdrant-edge. Also use when deciding what Edge ships built-in versus what you must implement.",
     "tokens_meta": 126,
     "tokens_body": 1341,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-migration-tool",
     "path": "lib/skills/qdrant-migration-tool",
     "description": "Guides use of the Qdrant Migration Tool CLI to move vectors, metadata, and sparse embeddings from another vector database into Qdrant. Use when someone asks 'how do I migrate from Pinecone/Weaviate/Milvus/Elasticsearch/OpenSearch/pgvector/s3/Azure/Chroma/Redis/MongoDB/FAISS/Solr to Qdrant', 'move my vector database to Qdrant', 'is there a migration tool for Qdrant', 'my migration got interrupted, how do I resume it', 'migration is too slow', or 'collection wasn't created after migration'. Also use when picking migration batch size, deciding on `--net=host`, or verifying data after a migration.",
     "tokens_meta": 155,
     "tokens_body": 1913,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-model-migration",
     "path": "lib/skills/qdrant-model-migration",
     "description": "Guides embedding model migration in Qdrant without downtime. Use when someone asks 'how to switch embedding models', 'how to migrate vectors', 'how to update to a new model', 'zero-downtime model change', 'how to re-embed my data', or 'can I use two models at once'. Also use when upgrading model dimensions, switching providers, or A/B testing models.",
     "tokens_meta": 94,
     "tokens_body": 1702,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-monitoring",
     "path": "lib/skills/qdrant-monitoring",
     "description": "Guides Qdrant monitoring and observability setup. Use when someone asks 'how to monitor Qdrant', 'what metrics to track', 'is Qdrant healthy', 'optimizer stuck', 'why is memory growing', 'requests are slow', 'set up alerts', 'cluster health check', or needs to set up Prometheus, Grafana, health checks, or log centralization. Also use when debugging production issues that require metric analysis.",
     "tokens_meta": 104,
     "tokens_body": 367,
     "tokens_dir": 1778,
     "files": 3,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-multitenancy",
     "path": "lib/skills/qdrant-multitenancy",
     "description": "Guides tenant isolation architecture in Qdrant for multi-tenant or multi-user applications. Use when someone asks 'how to isolate customer data', 'how to build multi-tenant search/RAG', 'how many collections should I create', 'how to partition tenants by payload', 'a customer's data legally has to stay in a certain country or region'. Also use when they describe a symptom: one customer's data is way bigger than the rest and slowing everyone down, or one tenant is hogging resources.",
     "tokens_meta": 126,
     "tokens_body": 1622,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-performance-optimization",
     "path": "lib/skills/qdrant-performance-optimization",
     "description": "Navigation hub linking sub-skills for proactive Qdrant tuning: search speed, indexing performance, and memory usage optimization. Use when planning configuration or capacity changes to improve speed and efficiency. For diagnosing an active production slowdown or analyzing live metrics, use qdrant-monitoring instead.",
     "tokens_meta": 87,
     "tokens_body": 456,
     "tokens_dir": 3985,
     "files": 4,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-scaling",
     "path": "lib/skills/qdrant-scaling",
     "description": "Guides Qdrant scaling decisions. Use when someone asks 'how many nodes do I need', 'data doesn't fit on one node', 'need more throughput or QPS', 'CPU is pegged / can't keep up with the request rate', 'one query is slow / p99 or tail latency too high', 'cluster is slow', 'too many tenants', 'vertical or horizontal', 'how to shard', 'need to add capacity', 'large limit / pagination / scroll is slow', or 'only recent data matters / expiring old vectors / retention window'.",
     "tokens_meta": 122,
     "tokens_body": 601,
     "tokens_dir": 6441,
     "files": 9,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-search-quality",
     "path": "lib/skills/qdrant-search-quality",
     "description": "Diagnoses and improves Qdrant search relevance. Use when someone reports 'search results are bad', 'wrong results', 'low precision', 'low recall', 'irrelevant matches', 'missing expected results', or asks 'how to improve search quality?', 'which embedding model?', 'should I use hybrid search?', 'how to combine keyword and vector search / fusion / RRF / prefetch?', 'should I use reranking?', 'relevance feedback?', 'how to measure retrieval quality?', 'build a golden set', 'ground truth dataset', or 'how to score recall@k?'. Also use when search quality degrades after quantization, model change, or data growth.",
     "tokens_meta": 159,
     "tokens_body": 565,
     "tokens_dir": 10025,
     "files": 7,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-sizing",
     "path": "lib/skills/qdrant-sizing",
     "description": "Sizes a Qdrant deployment before it is provisioned. Use when someone asks 'how much RAM do I need', 'how many nodes', 'how big should my cluster be', 'sizing', 'capacity planning', 'will N vectors fit', 'what instance type should I pick', or gives a vector count and dimensions and asks what to provision. Also use when an existing estimate needs checking before hardware or a cluster tier is bought.",
     "tokens_meta": 103,
     "tokens_body": 2356,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    },
    {
     "kind": "skill",
     "name": "qdrant-version-upgrade",
     "path": "lib/skills/qdrant-version-upgrade",
     "description": "Covers upgrading Qdrant server and SDKs without interrupting availability or losing data integrity. Use when someone asks 'how do I upgrade Qdrant', 'can I jump from 1.15 to 1.18', 'rolling upgrade without downtime', 'do I upgrade the client or the server first', 'which SDK version matches my server', 'what should I check before upgrading', or 'something changed after we upgraded'.",
     "tokens_meta": 102,
     "tokens_body": 1348,
     "tokens_dir": 0,
     "files": 1,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": null,
   "view": {
    "title": "qdrant",
    "verdict": null,
    "pitch": null,
    "sections": [],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": null,
   "size": null,
   "security": null,
   "economy": {
    "always_on": 1293,
    "partial": false,
    "idle_pct": 4.2254901960784315,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/plugins/qdrant.json"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/catalog/plugin-qdrant/REVIEW.md",
    "label": "catalog/plugin-qdrant/REVIEW.md",
    "repo": null
   },
   "install": {
    "id": "qdrant@acb",
    "cmd": "claude plugin install qdrant@acb",
    "try": "claude --plugin-dir catalog/plugin-qdrant"
   },
   "artifact": null
  },
  {
   "id": "skill-caveman",
   "kind": "skill",
   "name": "caveman",
   "dir": "catalog/skill-caveman",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "caveman",
     "path": "lib/skills/caveman",
     "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
     "tokens_meta": 59,
     "tokens_body": 1708,
     "tokens_dir": 489,
     "files": 2,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/JuliusBrussee/caveman/tree/main/skills/caveman",
    "title": "Compressed answers in caveman style",
    "verdict": "taste",
    "rating": 3.5,
    "security": 4.5,
    "economy": "-5%",
    "body": "## Summary\nWhen you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. \nMore experimental\n\n## Examples\n- \"Why does the component re-render?\" => instead of \"Sure! I'd be happy to help…\" the answer is three fragments: \"New object ref each render. Inline object prop = new ref = re-render. Wrap in `useMemo`.\"\n- DROP TABLE in a plan => Auto-Clarity lifts the compression, the warning about irreversibility comes in ordinary prose, then the style comes back; commits, docs and the issue body are outside the compression too\n\n## Notes\nCommits, documentation and warnings about anything dangerous are excluded from the compression\nFrom the repository we take only skills/caveman\nCloser to a person's style",
    "use": "When you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. More experimental"
   },
   "view": {
    "title": "Compressed answers in caveman style",
    "verdict": "taste",
    "pitch": "When you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. More experimental",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Why does the component re-render?\" => instead of \"Sure! I'd be happy to help…\" the answer is three fragments: \"New object ref each render. Inline object prop = new ref = re-render. Wrap in `useMemo`.\"\n- DROP TABLE in a plan => Auto-Clarity lifts the compression, the warning about irreversibility comes in ordinary prose, then the style comes back; commits, docs and the issue body are outside the compression too"
     },
     {
      "title": "Notes",
      "text": "Commits, documentation and warnings about anything dangerous are excluded from the compression\nFrom the repository we take only skills/caveman\nCloser to a person's style"
     }
    ],
    "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
    "category": null,
    "tags": []
   },
   "rating": 3.5,
   "size": 1708,
   "security": 4.5,
   "economy": {
    "always_on": 59,
    "partial": false,
    "idle_pct": 0.19281045751633985,
    "pct": -5,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/caveman"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/JuliusBrussee/caveman/tree/main/skills/caveman",
    "label": "JuliusBrussee/caveman/skills/caveman",
    "repo": "JuliusBrussee/caveman"
   },
   "install": {
    "id": "caveman@acb",
    "cmd": "claude plugin install caveman@acb",
    "try": "claude --plugin-dir catalog/skill-caveman"
   },
   "artifact": {
    "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
    "fm_name": "caveman",
    "tokens_meta": 59,
    "tokens_body": 1708,
    "tokens_dir": 489,
    "files": 2,
    "has_scripts": false
   }
  },
  {
   "id": "skill-claude-api",
   "kind": "skill",
   "name": "claude-api",
   "dir": "catalog/skill-claude-api",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "claude-api",
     "path": "lib/skills/claude-api",
     "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
     "tokens_meta": 270,
     "tokens_body": 21543,
     "tokens_dir": 276355,
     "files": 70,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
    "title": "Claude API: models, SDK, migrations",
    "verdict": "stack",
    "rating": 5,
    "security": 4.5,
    "economy": "+3%",
    "body": "## Summary\nWhen the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK\n\n## Examples\n- \"A script on the Anthropic SDK: Opus 5 with server-side web search, no more than 3 searches\" => without it, from memory puts the outdated `web_search_20250305`; with it, the current `web_search_20260209`, `claude-opus-5`, `max_uses: 3` — the code runs as is\n- With the skill it picks a more current model (not sonnet-3.5; it fairly puts the latest sonnet-5)\n\n## Notes\nThe most expensive to activate: SKILL.md ≈ 22k tokens on every activation, so only into projects that really write code on the Anthropic SDK\nsecurity: 4.5 - official Anthropic plugin, but it can go to the network and take credential tokens;",
    "use": "When the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK"
   },
   "view": {
    "title": "Claude API: models, SDK, migrations",
    "verdict": "stack",
    "pitch": "When the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"A script on the Anthropic SDK: Opus 5 with server-side web search, no more than 3 searches\" => without it, from memory puts the outdated `web_search_20250305`; with it, the current `web_search_20260209`, `claude-opus-5`, `max_uses: 3` — the code runs as is\n- With the skill it picks a more current model (not sonnet-3.5; it fairly puts the latest sonnet-5)"
     },
     {
      "title": "Notes",
      "text": "The most expensive to activate: SKILL.md ≈ 22k tokens on every activation, so only into projects that really write code on the Anthropic SDK\nsecurity: 4.5 - official Anthropic plugin, but it can go to the network and take credential tokens;"
     }
    ],
    "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 21543,
   "security": 4.5,
   "economy": {
    "always_on": 270,
    "partial": false,
    "idle_pct": 0.8823529411764706,
    "pct": 3,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-web-search-server-tool"
    ],
    "runs": 1,
    "latest": {
     "score": 1,
     "delta": 0.5,
     "pass_rate": 1,
     "cases": 1,
     "passed": 1,
     "cost_usd": 0.6227555,
     "version": "2.1.272",
     "at": "2026-09-15",
     "partial": false,
     "report": "catalog/skill-claude-api/evals/results/2026-09-15T10-54-16-976Z/report.html",
     "dir": "catalog/skill-claude-api/evals/results/2026-09-15T10-54-16-976Z",
     "per_case": [
      {
       "name": "01-web-search-server-tool",
       "score": 1,
       "without": 0.5,
       "delta": 0.5
      }
     ]
    },
    "cmd": "python3 ui/eval.py lib/skills/claude-api"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
    "label": "anthropics/skills/skills/claude-api",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "claude-api@acb",
    "cmd": "claude plugin install claude-api@acb",
    "try": "claude --plugin-dir catalog/skill-claude-api"
   },
   "artifact": {
    "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
    "fm_name": "claude-api",
    "tokens_meta": 270,
    "tokens_body": 21543,
    "tokens_dir": 276355,
    "files": 70,
    "has_scripts": false
   }
  },
  {
   "id": "skill-docx",
   "kind": "skill",
   "name": "docx",
   "dir": "catalog/skill-docx",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "docx",
     "path": "lib/skills/docx",
     "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
     "tokens_meta": 210,
     "tokens_body": 1717,
     "tokens_dir": 286322,
     "files": 61,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "title": "Word documents: creating and editing",
    "verdict": "task",
    "rating": 5,
    "security": 5,
    "economy": "+1%",
    "body": "## Summary\nWhen you need to fix up a .docx (touch up a CV, produce a solid report with tables)\n\n## Examples\n- \"Make the edits to the contract as tracked changes\" => the edit is easy to insert without `<w:ins>`/`<w:del>`, and in accepted view it is invisible; `validate.py --original doc.docx --author \"<name>\"` shows every untracked one\n- \"Add langchain to my stack at my last job\" => Without the skill everything would shift and you would have to fix it by hand\n\n## Notes\nFor .docx there are no alternatives, install for the duration of work with documents\nsecurity: 5 - official Anthropic plugin",
    "use": "When you need to fix up a .docx (touch up a CV, produce a solid report with tables)"
   },
   "view": {
    "title": "Word documents: creating and editing",
    "verdict": "task",
    "pitch": "When you need to fix up a .docx (touch up a CV, produce a solid report with tables)",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Make the edits to the contract as tracked changes\" => the edit is easy to insert without `<w:ins>`/`<w:del>`, and in accepted view it is invisible; `validate.py --original doc.docx --author \"<name>\"` shows every untracked one\n- \"Add langchain to my stack at my last job\" => Without the skill everything would shift and you would have to fix it by hand"
     },
     {
      "title": "Notes",
      "text": "For .docx there are no alternatives, install for the duration of work with documents\nsecurity: 5 - official Anthropic plugin"
     }
    ],
    "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 1717,
   "security": 5,
   "economy": {
    "always_on": 210,
    "partial": false,
    "idle_pct": 0.6862745098039216,
    "pct": 1,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/docx"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "label": "anthropics/skills/skills/docx",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "docx@acb",
    "cmd": "claude plugin install docx@acb",
    "try": "claude --plugin-dir catalog/skill-docx"
   },
   "artifact": {
    "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
    "fm_name": "docx",
    "tokens_meta": 210,
    "tokens_body": 1717,
    "tokens_dir": 286322,
    "files": 61,
    "has_scripts": false
   }
  },
  {
   "id": "skill-mcp-builder",
   "kind": "skill",
   "name": "mcp-builder",
   "dir": "catalog/skill-mcp-builder",
   "status": "draft",
   "members": [
    {
     "kind": "skill",
     "name": "mcp-builder",
     "path": "lib/skills/mcp-builder",
     "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
     "tokens_meta": 72,
     "tokens_body": 2267,
     "tokens_dir": 28988,
     "files": 10,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": null,
   "view": {
    "title": "mcp-builder",
    "verdict": null,
    "pitch": null,
    "sections": [],
    "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
    "category": null,
    "tags": []
   },
   "rating": null,
   "size": 2267,
   "security": null,
   "economy": {
    "always_on": 72,
    "partial": false,
    "idle_pct": 0.2352941176470588,
    "pct": null,
    "from": null,
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/mcp-builder"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": false
   },
   "reviewed_at": null,
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/lib/skills/mcp-builder",
    "label": "lib/skills/mcp-builder",
    "repo": null
   },
   "install": {
    "id": "mcp-builder@acb",
    "cmd": "claude plugin install mcp-builder@acb",
    "try": "claude --plugin-dir catalog/skill-mcp-builder"
   },
   "artifact": {
    "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
    "fm_name": "mcp-builder",
    "tokens_meta": 72,
    "tokens_body": 2267,
    "tokens_dir": 28988,
    "files": 10,
    "has_scripts": false
   }
  },
  {
   "id": "skill-skill-creator",
   "kind": "skill",
   "name": "skill-creator",
   "dir": "catalog/skill-skill-creator",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "skill-creator",
     "path": "lib/skills/skill-creator",
     "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
     "tokens_meta": 83,
     "tokens_body": 8247,
     "tokens_dir": 49248,
     "files": 18,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    "title": "Creating and evaluating Agent Skills",
    "verdict": "task",
    "rating": 4,
    "security": 3,
    "economy": "+31%",
    "body": "## Summary\nWhen you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description.\n\n## Examples\n- \"Make a skill for X\" => first four questions (what it can do, which phrases trigger it, output format, are tests needed), then a draft and test prompts, instead of a SKILL.md by guesswork\n- The skill does not trigger on the right requests => `scripts/run_loop.py` splits the requests 60/40 into train and held-out, runs each 3 times, edits the description for up to 5 iterations and returns `best_description` by held-out\n\n## Notes\nThe most expensive activation among the \"For a task\" ones: +31% per session, the description tuning loop is 20 requests × 3 runs × up to 5 iterations.\nThe scripts write to ~/.claude/commands and /tmp.",
    "use": "When you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description."
   },
   "view": {
    "title": "Creating and evaluating Agent Skills",
    "verdict": "task",
    "pitch": "When you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description.",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Make a skill for X\" => first four questions (what it can do, which phrases trigger it, output format, are tests needed), then a draft and test prompts, instead of a SKILL.md by guesswork\n- The skill does not trigger on the right requests => `scripts/run_loop.py` splits the requests 60/40 into train and held-out, runs each 3 times, edits the description for up to 5 iterations and returns `best_description` by held-out"
     },
     {
      "title": "Notes",
      "text": "The most expensive activation among the \"For a task\" ones: +31% per session, the description tuning loop is 20 requests × 3 runs × up to 5 iterations.\nThe scripts write to ~/.claude/commands and /tmp."
     }
    ],
    "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
    "category": null,
    "tags": []
   },
   "rating": 4,
   "size": 8247,
   "security": 3,
   "economy": {
    "always_on": 83,
    "partial": false,
    "idle_pct": 0.27124183006535946,
    "pct": 31,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/skill-creator"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    "label": "anthropics/skills/skills/skill-creator",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "skill-creator@acb",
    "cmd": "claude plugin install skill-creator@acb",
    "try": "claude --plugin-dir catalog/skill-skill-creator"
   },
   "artifact": {
    "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
    "fm_name": "skill-creator",
    "tokens_meta": 83,
    "tokens_body": 8247,
    "tokens_dir": 49248,
    "files": 18,
    "has_scripts": false
   }
  }
 ]
};
