// generated by ui/build.py — do not edit by hand
window.CATALOG = {
 "generated_at": "2026-09-16 08:41",
 "git": true,
 "marketplace": {
  "name": "acb",
  "repo": "innowise-ai/ai-ml-accelerator"
 },
 "session_model": {
  "_": "The typical session the «Token cost» column is measured against: turns model calls, each with context_tokens of input and output_tokens of output. Δ% = (standing cost × turns + per-call cost × calls + behavioural effect) / (turns × (context + output)). MCP: if the tool schemas exceed mcp_defer_over_tokens, Claude Code loads them deferred and only the names stay in context (mcp_deferred_tokens_per_tool per tool).",
  "turns": 40,
  "context_tokens": 30000,
  "output_tokens": 600,
  "mcp_defer_over_tokens": 5000,
  "mcp_deferred_tokens_per_tool": 15
 },
 "verdicts": {
  "must-have": {
   "label": "Must have",
   "hint": "into any project by default: almost always pays off, no conditions"
  },
  "stack": {
   "label": "For the stack",
   "hint": "if the project uses the technology or service from the description"
  },
  "task": {
   "label": "For a task",
   "hint": "for the duration of a specific job, then remove; usually expensive on activation"
  },
  "taste": {
   "label": "Taste",
   "hint": "a person's working style, not the project's; install into ~/.claude"
  },
  "no": {
   "label": "Don't install",
   "hint": "rejected by the reviewer; the entry stays as a warning"
  }
 },
 "kinds": [
  {
   "kind": "skill",
   "label": "Skills"
  },
  {
   "kind": "agent",
   "label": "Agents"
  },
  {
   "kind": "mcp",
   "label": "MCP servers"
  },
  {
   "kind": "hook",
   "label": "Hooks"
  },
  {
   "kind": "plugin",
   "label": "Bundles"
  }
 ],
 "library": {
  "skill": [
   "build-review-interface",
   "caveman",
   "claude-api",
   "deep-agents-core",
   "deep-agents-memory",
   "deep-agents-orchestration",
   "deepagents-python-quickstart",
   "deepagents-typescript-quickstart",
   "docx",
   "ecosystem-primer",
   "error-discovery",
   "eval-audit",
   "eval-engineering",
   "evals-start",
   "evaluate-rag",
   "generate-synthetic-data",
   "langchain-dependencies",
   "langchain-fundamentals",
   "langchain-middleware",
   "langchain-python-quickstart",
   "langchain-rag",
   "langchain-typescript-quickstart",
   "langgraph-cli",
   "langgraph-fundamentals",
   "langgraph-human-in-the-loop",
   "langgraph-persistence",
   "langgraph-python-quickstart",
   "langgraph-typescript-quickstart",
   "langsmith-online-eval-engineering",
   "managed-deep-agents",
   "mcp-builder",
   "qdrant-clients-sdk",
   "qdrant-deployment-options",
   "qdrant-edge",
   "qdrant-migration-tool",
   "qdrant-model-migration",
   "qdrant-monitoring",
   "qdrant-multitenancy",
   "qdrant-performance-optimization",
   "qdrant-scaling",
   "qdrant-search-quality",
   "qdrant-sizing",
   "qdrant-version-upgrade",
   "skill-creator",
   "swarm",
   "validate-evaluator",
   "write-judge-prompt"
  ],
  "agent": [],
  "mcp": [
   "context7",
   "github"
  ],
  "hook": [
   "notify-done"
  ]
 },
 "compositions": {
  "base": {
   "skill": [],
   "agent": [],
   "mcp": [
    "context7"
   ],
   "hook": [
    "notify-done"
   ]
  },
  "evals": {
   "skill": [
    "evals-start",
    "eval-audit",
    "error-discovery",
    "write-judge-prompt",
    "validate-evaluator",
    "generate-synthetic-data",
    "evaluate-rag",
    "build-review-interface"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "langchain": {
   "skill": [
    "deep-agents-core",
    "deep-agents-memory",
    "deep-agents-orchestration",
    "deepagents-python-quickstart",
    "deepagents-typescript-quickstart",
    "ecosystem-primer",
    "eval-engineering",
    "langchain-dependencies",
    "langchain-fundamentals",
    "langchain-middleware",
    "langchain-python-quickstart",
    "langchain-rag",
    "langchain-typescript-quickstart",
    "langgraph-cli",
    "langgraph-fundamentals",
    "langgraph-human-in-the-loop",
    "langgraph-persistence",
    "langgraph-python-quickstart",
    "langgraph-typescript-quickstart",
    "langsmith-online-eval-engineering",
    "managed-deep-agents",
    "swarm"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  },
  "qdrant": {
   "skill": [
    "qdrant-clients-sdk",
    "qdrant-deployment-options",
    "qdrant-edge",
    "qdrant-migration-tool",
    "qdrant-model-migration",
    "qdrant-monitoring",
    "qdrant-multitenancy",
    "qdrant-performance-optimization",
    "qdrant-scaling",
    "qdrant-search-quality",
    "qdrant-sizing",
    "qdrant-version-upgrade"
   ],
   "agent": [],
   "mcp": [],
   "hook": []
  }
 },
 "items": [
  {
   "id": "hook-notify-done",
   "kind": "hook",
   "name": "notify-done",
   "dir": "catalog/hook-notify-done",
   "status": "reviewed",
   "members": [
    {
     "kind": "hook",
     "name": "notify-done",
     "path": "lib/hooks/notify-done",
     "description": null,
     "events": [
      "Stop"
     ],
     "scripts": [
      "notify-done.sh"
     ]
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "taste",
    "rating": 4,
    "security": 5,
    "economy": "0%",
    "body": "## Summary\nWhen several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing.\n\n## Notes\nCustom hook on the Stop event; osascript on macOS, notify-send on Linux, no network\nDoes not land in the prompt — 0 tokens",
    "use": "When several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing."
   },
   "view": {
    "title": "notify-done",
    "verdict": "taste",
    "pitch": "When several sessions run in parallel: a system notification as soon as Claude has finished its turn and is waiting. Costs nothing.",
    "sections": [
     {
      "title": "Notes",
      "text": "Custom hook on the Stop event; osascript on macOS, notify-send on Linux, no network\nDoes not land in the prompt — 0 tokens"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 4,
   "size": null,
   "security": 5,
   "economy": {
    "always_on": 0,
    "partial": false,
    "idle_pct": 0,
    "pct": 0,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/hooks/notify-done"
   },
   "flags": {
    "official": false,
    "own": true,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": true,
    "url": "https://github.com/innowise-ai/ai-ml-accelerator/blob/main/lib/hooks/notify-done",
    "label": "lib/hooks/notify-done",
    "repo": null
   },
   "install": {
    "id": "notify-done@acb",
    "cmd": "claude plugin install notify-done@acb",
    "try": "claude --plugin-dir catalog/hook-notify-done"
   },
   "artifact": null
  },
  {
   "id": "mcp-context7",
   "kind": "mcp",
   "name": "context7",
   "dir": "catalog/mcp-context7",
   "status": "reviewed",
   "members": [
    {
     "kind": "mcp",
     "name": "context7",
     "path": "lib/mcp/context7.json",
     "description": null,
     "type": "http",
     "url": "https://mcp.context7.com/mcp",
     "command": null,
     "env_required": []
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "must-have",
    "rating": 5,
    "security": 4,
    "economy": "+4%",
    "full-body": "1.2k",
    "body": "## Summary\nPulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off.\n\n## Examples\n- We want to build an agent on LangGraph => with it, takes the modern create_agent abstraction from langchain v1 instead of a tool loop from scratch\n- Updated the Vercel AI SDK, `maxSteps` is gone => without it, writes `stepCountIs` from v5 from memory, with it, takes the current `isStepCount`\n\n## Notes\nOne of the most popular and convenient MCPs;\nThe answer averages 3.5k tokens (on average 3-5 per session)\nFires almost always (for me ~80% of sessions)\nSafe; only the library name and the topic of the request go out, no code goes out",
    "use": "Pulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off."
   },
   "view": {
    "title": "context7",
    "verdict": "must-have",
    "pitch": "Pulls up the current documentation of libraries. Just RAG over current, continuously updated documentation. Almost always pays off.",
    "sections": [
     {
      "title": "Examples",
      "text": "- We want to build an agent on LangGraph => with it, takes the modern create_agent abstraction from langchain v1 instead of a tool loop from scratch\n- Updated the Vercel AI SDK, `maxSteps` is gone => without it, writes `stepCountIs` from v5 from memory, with it, takes the current `isStepCount`"
     },
     {
      "title": "Notes",
      "text": "One of the most popular and convenient MCPs;\nThe answer averages 3.5k tokens (on average 3-5 per session)\nFires almost always (for me ~80% of sessions)\nSafe; only the library name and the topic of the request go out, no code goes out"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 1200,
   "security": 4,
   "economy": {
    "always_on": null,
    "partial": false,
    "idle_pct": null,
    "pct": 4,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-langchain-create-agent",
     "02-ai-sdk-stop-condition"
    ],
    "runs": 1,
    "latest": {
     "score": 1,
     "delta": 0.5833333333333334,
     "pass_rate": 1,
     "cases": 2,
     "passed": 2,
     "cost_usd": 0.8477839999999999,
     "version": "2.1.272",
     "at": "2026-09-15",
     "partial": false,
     "report": "catalog/mcp-context7/evals/results/2026-09-15T09-41-46-156Z/report.html",
     "dir": "catalog/mcp-context7/evals/results/2026-09-15T09-41-46-156Z",
     "per_case": [
      {
       "name": "01-langchain-create-agent",
       "score": 1,
       "without": 0.5,
       "delta": 0.5
      },
      {
       "name": "02-ai-sdk-stop-condition",
       "score": 1,
       "without": 0.3333333333333333,
       "delta": 0.6666666666666667
      }
     ]
    },
    "cmd": "python3 ui/eval.py lib/mcp/context7.json"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/upstash/context7",
    "label": "upstash/context7",
    "repo": "upstash/context7"
   },
   "install": {
    "id": "context7@acb",
    "cmd": "claude plugin install context7@acb",
    "try": "claude --plugin-dir catalog/mcp-context7"
   },
   "artifact": null
  },
  {
   "id": "mcp-github",
   "kind": "mcp",
   "name": "github",
   "dir": "catalog/mcp-github",
   "status": "reviewed",
   "members": [
    {
     "kind": "mcp",
     "name": "github",
     "path": "lib/mcp/github.json",
     "description": null,
     "type": "http",
     "url": "https://api.githubcopilot.com/mcp/",
     "command": null,
     "env_required": [
      "GITHUB_PAT"
     ]
    }
   ],
   "bundles": [],
   "review": {
    "verdict": "must-have",
    "rating": 5,
    "security": 3.5,
    "economy": "+3%",
    "full-body": 600,
    "body": "## Summary\nWhen the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions\n\n## Examples\n- \"Open a PR from this branch and reply to the reviewer\" => `create_pull_request` and `add_reply_to_pull_request_comment` straight from the session, without gh CLI and without the web\n- CI failed => `get_job_logs` with `failed_only: true` returns the logs of every failed job of one run, instead of copy-paste from Actions or switching to browser using tools\n\n## Notes\nI use it constantly\nSchemas of ~40 tools ≈ 18k tok, but Claude Code loads them deferred: ≈ 600 tok of names in the context, the schema is pulled in on call\nThe token goes only to the official GitHub server, where the code already lives anyway",
    "use": "When the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions"
   },
   "view": {
    "title": "github",
    "verdict": "must-have",
    "pitch": "When the project is on GitHub: the agent opens PRs and issues itself, reads reviews and the logs of failed Actions",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Open a PR from this branch and reply to the reviewer\" => `create_pull_request` and `add_reply_to_pull_request_comment` straight from the session, without gh CLI and without the web\n- CI failed => `get_job_logs` with `failed_only: true` returns the logs of every failed job of one run, instead of copy-paste from Actions or switching to browser using tools"
     },
     {
      "title": "Notes",
      "text": "I use it constantly\nSchemas of ~40 tools ≈ 18k tok, but Claude Code loads them deferred: ≈ 600 tok of names in the context, the schema is pulled in on call\nThe token goes only to the official GitHub server, where the code already lives anyway"
     }
    ],
    "description": null,
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 600,
   "security": 3.5,
   "economy": {
    "always_on": null,
    "partial": false,
    "idle_pct": null,
    "pct": 3,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/mcp/github.json"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/github/github-mcp-server",
    "label": "github/github-mcp-server",
    "repo": "github/github-mcp-server"
   },
   "install": {
    "id": "github@acb",
    "cmd": "claude plugin install github@acb",
    "try": "claude --plugin-dir catalog/mcp-github"
   },
   "artifact": null
  },
  {
   "id": "skill-caveman",
   "kind": "skill",
   "name": "caveman",
   "dir": "catalog/skill-caveman",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "caveman",
     "path": "lib/skills/caveman",
     "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
     "tokens_meta": 59,
     "tokens_body": 1708,
     "tokens_dir": 476,
     "files": 2,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/JuliusBrussee/caveman/tree/main/skills/caveman",
    "title": "Compressed answers in caveman style",
    "verdict": "taste",
    "rating": 3.5,
    "security": 4.5,
    "economy": "-5%",
    "body": "## Summary\nWhen you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. \nMore experimental\n\n## Examples\n- \"Why does the component re-render?\" => instead of \"Sure! I'd be happy to help…\" the answer is three fragments: \"New object ref each render. Inline object prop = new ref = re-render. Wrap in `useMemo`.\"\n- DROP TABLE in a plan => Auto-Clarity lifts the compression, the warning about irreversibility comes in ordinary prose, then the style comes back; commits, docs and the issue body are outside the compression too\n\n## Notes\nCommits, documentation and warnings about anything dangerous are excluded from the compression\nFrom the repository we take only skills/caveman\nCloser to a person's style",
    "use": "When you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. More experimental"
   },
   "view": {
    "title": "Compressed answers in caveman style",
    "verdict": "taste",
    "pitch": "When you need short answers: cuts the preamble and the articles, keeping code, errors and warnings about dangerous operations. More experimental",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Why does the component re-render?\" => instead of \"Sure! I'd be happy to help…\" the answer is three fragments: \"New object ref each render. Inline object prop = new ref = re-render. Wrap in `useMemo`.\"\n- DROP TABLE in a plan => Auto-Clarity lifts the compression, the warning about irreversibility comes in ordinary prose, then the style comes back; commits, docs and the issue body are outside the compression too"
     },
     {
      "title": "Notes",
      "text": "Commits, documentation and warnings about anything dangerous are excluded from the compression\nFrom the repository we take only skills/caveman\nCloser to a person's style"
     }
    ],
    "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
    "category": null,
    "tags": []
   },
   "rating": 3.5,
   "size": 1708,
   "security": 4.5,
   "economy": {
    "always_on": 59,
    "partial": false,
    "idle_pct": 0.19281045751633985,
    "pct": -5,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/caveman"
   },
   "flags": {
    "official": false,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/JuliusBrussee/caveman/tree/main/skills/caveman",
    "label": "JuliusBrussee/caveman/skills/caveman",
    "repo": "JuliusBrussee/caveman"
   },
   "install": {
    "id": "caveman@acb",
    "cmd": "claude plugin install caveman@acb",
    "try": "claude --plugin-dir catalog/skill-caveman"
   },
   "artifact": {
    "description": "Ultra-compressed communication mode that cuts output tokens while keeping technical accuracy. Levels: lite, full, ultra and the wenyan variants. Use for /caveman, \"caveman mode\", \"talk like caveman\", \"be brief\" or \"less tokens\".",
    "fm_name": "caveman",
    "tokens_meta": 59,
    "tokens_body": 1708,
    "tokens_dir": 476,
    "files": 2,
    "has_scripts": false
   }
  },
  {
   "id": "skill-claude-api",
   "kind": "skill",
   "name": "claude-api",
   "dir": "catalog/skill-claude-api",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "claude-api",
     "path": "lib/skills/claude-api",
     "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
     "tokens_meta": 270,
     "tokens_body": 21543,
     "tokens_dir": 272151,
     "files": 70,
     "has_scripts": false
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
    "title": "Claude API: models, SDK, migrations",
    "verdict": "stack",
    "rating": 5,
    "security": 4.5,
    "economy": "+3%",
    "body": "## Summary\nWhen the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK\n\n## Examples\n- \"A script on the Anthropic SDK: Opus 5 with server-side web search, no more than 3 searches\" => without it, from memory puts the outdated `web_search_20250305`; with it, the current `web_search_20260209`, `claude-opus-5`, `max_uses: 3` — the code runs as is\n- With the skill it picks a more current model (not sonnet-3.5; it fairly puts the latest sonnet-5)\n\n## Notes\nThe most expensive to activate: SKILL.md ≈ 22k tokens on every activation, so only into projects that really write code on the Anthropic SDK\nsecurity: 4.5 - official Anthropic plugin, but it can go to the network and take credential tokens;",
    "use": "When the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK"
   },
   "view": {
    "title": "Claude API: models, SDK, migrations",
    "verdict": "stack",
    "pitch": "When the project calls the Claude API: current model ids and prices, adaptive thinking, caching, tool use, model migrations. Pays off in any code on the Anthropic SDK",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"A script on the Anthropic SDK: Opus 5 with server-side web search, no more than 3 searches\" => without it, from memory puts the outdated `web_search_20250305`; with it, the current `web_search_20260209`, `claude-opus-5`, `max_uses: 3` — the code runs as is\n- With the skill it picks a more current model (not sonnet-3.5; it fairly puts the latest sonnet-5)"
     },
     {
      "title": "Notes",
      "text": "The most expensive to activate: SKILL.md ≈ 22k tokens on every activation, so only into projects that really write code on the Anthropic SDK\nsecurity: 4.5 - official Anthropic plugin, but it can go to the network and take credential tokens;"
     }
    ],
    "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 21543,
   "security": 4.5,
   "economy": {
    "always_on": 270,
    "partial": false,
    "idle_pct": 0.8823529411764706,
    "pct": 3,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [
     "01-web-search-server-tool"
    ],
    "runs": 1,
    "latest": {
     "score": 1,
     "delta": 0.5,
     "pass_rate": 1,
     "cases": 1,
     "passed": 1,
     "cost_usd": 0.6227555,
     "version": "2.1.272",
     "at": "2026-09-15",
     "partial": false,
     "report": "catalog/skill-claude-api/evals/results/2026-09-15T10-54-16-976Z/report.html",
     "dir": "catalog/skill-claude-api/evals/results/2026-09-15T10-54-16-976Z",
     "per_case": [
      {
       "name": "01-web-search-server-tool",
       "score": 1,
       "without": 0.5,
       "delta": 0.5
      }
     ]
    },
    "cmd": "python3 ui/eval.py lib/skills/claude-api"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/claude-api",
    "label": "anthropics/skills/skills/claude-api",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "claude-api@acb",
    "cmd": "claude plugin install claude-api@acb",
    "try": "claude --plugin-dir catalog/skill-claude-api"
   },
   "artifact": {
    "description": "Reference for the Claude API / Anthropic SDK — model ids, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration. TRIGGER — read BEFORE opening the target file; don't skip because it \"looks like a one-liner\" — whenever: the prompt names Claude/Anthropic in any form (Claude, Anthropic, Fable, Opus, Sonnet, Haiku, `anthropic`, `@anthropic-ai`, `claude-*`, `us.anthropic.*`, `[1m]`); the user asks about an LLM (pricing/model choice/limits/caching) — never answer from memory; OR the task is LLM-shaped with provider unstated (agent/MCP/tool-definition/multi-agent/RAG/LLM-judge/computer-use; generate/summarize/extract/classify/rewrite/converse over NL; debugging refusals/cutoffs/streaming/tool-calls/tokens). SKIP only when another provider is being worked on (overrides all triggers): OpenAI/GPT/Gemini/Llama/Mistral/Cohere/Ollama named in the query; OR `grep -rE 'openai|langchain_openai|google.generativeai|genai|mistralai|cohere|ollama'` over the project hits (run this grep FIRST if no provider named — don't Read the file).",
    "fm_name": "claude-api",
    "tokens_meta": 270,
    "tokens_body": 21543,
    "tokens_dir": 272151,
    "files": 70,
    "has_scripts": false
   }
  },
  {
   "id": "skill-docx",
   "kind": "skill",
   "name": "docx",
   "dir": "catalog/skill-docx",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "docx",
     "path": "lib/skills/docx",
     "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
     "tokens_meta": 210,
     "tokens_body": 1717,
     "tokens_dir": 280446,
     "files": 61,
     "has_scripts": true
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "title": "Word documents: creating and editing",
    "verdict": "task",
    "rating": 5,
    "security": 5,
    "economy": "+1%",
    "body": "## Summary\nWhen you need to fix up a .docx (touch up a CV, produce a solid report with tables)\n\n## Examples\n- \"Make the edits to the contract as tracked changes\" => the edit is easy to insert without `<w:ins>`/`<w:del>`, and in accepted view it is invisible; `validate.py --original doc.docx --author \"<name>\"` shows every untracked one\n- \"Add langchain to my stack at my last job\" => Without the skill everything would shift and you would have to fix it by hand\n\n## Notes\nFor .docx there are no alternatives, install for the duration of work with documents\nsecurity: 5 - official Anthropic plugin",
    "use": "When you need to fix up a .docx (touch up a CV, produce a solid report with tables)"
   },
   "view": {
    "title": "Word documents: creating and editing",
    "verdict": "task",
    "pitch": "When you need to fix up a .docx (touch up a CV, produce a solid report with tables)",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Make the edits to the contract as tracked changes\" => the edit is easy to insert without `<w:ins>`/`<w:del>`, and in accepted view it is invisible; `validate.py --original doc.docx --author \"<name>\"` shows every untracked one\n- \"Add langchain to my stack at my last job\" => Without the skill everything would shift and you would have to fix it by hand"
     },
     {
      "title": "Notes",
      "text": "For .docx there are no alternatives, install for the duration of work with documents\nsecurity: 5 - official Anthropic plugin"
     }
    ],
    "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
    "category": null,
    "tags": []
   },
   "rating": 5,
   "size": 1717,
   "security": 5,
   "economy": {
    "always_on": 210,
    "partial": false,
    "idle_pct": 0.6862745098039216,
    "pct": 1,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/docx"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
    "label": "anthropics/skills/skills/docx",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "docx@acb",
    "cmd": "claude plugin install docx@acb",
    "try": "claude --plugin-dir catalog/skill-docx"
   },
   "artifact": {
    "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
    "fm_name": "docx",
    "tokens_meta": 210,
    "tokens_body": 1717,
    "tokens_dir": 280446,
    "files": 61,
    "has_scripts": true
   }
  },
  {
   "id": "skill-skill-creator",
   "kind": "skill",
   "name": "skill-creator",
   "dir": "catalog/skill-skill-creator",
   "status": "reviewed",
   "members": [
    {
     "kind": "skill",
     "name": "skill-creator",
     "path": "lib/skills/skill-creator",
     "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
     "tokens_meta": 83,
     "tokens_body": 8247,
     "tokens_dir": 47956,
     "files": 18,
     "has_scripts": true
    }
   ],
   "bundles": [],
   "review": {
    "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    "title": "Creating and evaluating Agent Skills",
    "verdict": "task",
    "rating": 4,
    "security": 3,
    "economy": "+31%",
    "body": "## Summary\nWhen you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description.\n\n## Examples\n- \"Make a skill for X\" => first four questions (what it can do, which phrases trigger it, output format, are tests needed), then a draft and test prompts, instead of a SKILL.md by guesswork\n- The skill does not trigger on the right requests => `scripts/run_loop.py` splits the requests 60/40 into train and held-out, runs each 3 times, edits the description for up to 5 iterations and returns `best_description` by held-out\n\n## Notes\nThe most expensive activation among the \"For a task\" ones: +31% per session, the description tuning loop is 20 requests × 3 runs × up to 5 iterations.\nThe scripts write to ~/.claude/commands and /tmp.",
    "use": "When you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description."
   },
   "view": {
    "title": "Creating and evaluating Agent Skills",
    "verdict": "task",
    "pitch": "When you write or edit an Agent Skill: interview, draft, running evals with subagents, picking a description.",
    "sections": [
     {
      "title": "Examples",
      "text": "- \"Make a skill for X\" => first four questions (what it can do, which phrases trigger it, output format, are tests needed), then a draft and test prompts, instead of a SKILL.md by guesswork\n- The skill does not trigger on the right requests => `scripts/run_loop.py` splits the requests 60/40 into train and held-out, runs each 3 times, edits the description for up to 5 iterations and returns `best_description` by held-out"
     },
     {
      "title": "Notes",
      "text": "The most expensive activation among the \"For a task\" ones: +31% per session, the description tuning loop is 20 requests × 3 runs × up to 5 iterations.\nThe scripts write to ~/.claude/commands and /tmp."
     }
    ],
    "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
    "category": null,
    "tags": []
   },
   "rating": 4,
   "size": 8247,
   "security": 3,
   "economy": {
    "always_on": 83,
    "partial": false,
    "idle_pct": 0.27124183006535946,
    "pct": 31,
    "from": "human",
    "baseline": 1224000
   },
   "eval": {
    "cases": [],
    "runs": 0,
    "latest": null,
    "cmd": "python3 ui/eval.py lib/skills/skill-creator"
   },
   "flags": {
    "official": true,
    "own": false,
    "review_stale": false,
    "in_git": true
   },
   "reviewed_at": "2026-09-15",
   "source": {
    "own": false,
    "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    "label": "anthropics/skills/skills/skill-creator",
    "repo": "anthropics/skills"
   },
   "install": {
    "id": "skill-creator@acb",
    "cmd": "claude plugin install skill-creator@acb",
    "try": "claude --plugin-dir catalog/skill-skill-creator"
   },
   "artifact": {
    "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
    "fm_name": "skill-creator",
    "tokens_meta": 83,
    "tokens_body": 8247,
    "tokens_dir": 47956,
    "files": 18,
    "has_scripts": true
   }
  }
 ]
};
